import type { PosePresetId } from "../schema/poseSchema";
import type { PoseGroundContact } from "../runtime/mannequin/mannequinPose";

export interface PosePresetDefinition {
    id: PosePresetId;
    label: string;
    groundContact: PoseGroundContact;
    controls: Record<string, number>;
}

export const MANNEQUIN_POSE_PRESETS: PosePresetDefinition[] = [
    { id: "stand", label: "站立", groundContact: "both-feet", controls: {} },
    {
        id: "t-pose",
        label: "T型",
        groundContact: "both-feet",
        controls: {
            "leftShoulder.spread": -90,
            "rightShoulder.spread": 90,
        },
    },
    {
        id: "walk",
        label: "行走",
        groundContact: "left-foot",
        controls: {
            "body.pitch": 2,
            "torso.yaw": -4,
            "leftShoulder.pitch": -24,
            "rightShoulder.pitch": 24,
            "leftElbow.bend": 18,
            "rightElbow.bend": 8,
            "leftHip.pitch": 26,
            "rightHip.pitch": -22,
            "leftKnee.bend": 8,
            "rightKnee.bend": 25,
            "leftFoot.pitch": 18,
            "rightFoot.pitch": -47,
        },
    },
    {
        id: "run",
        label: "跑步",
        groundContact: "right-foot",
        controls: {
            "body.pitch": 8,
            "torso.yaw": 5,
            "leftShoulder.pitch": 45,
            "rightShoulder.pitch": -45,
            "leftElbow.bend": 78,
            "rightElbow.bend": 76,
            "leftHip.pitch": -25,
            "rightHip.pitch": 55,
            "leftKnee.bend": 18,
            "rightKnee.bend": 70,
            "leftFoot.pitch": -43,
            "rightFoot.pitch": -15,
        },
    },
    {
        id: "sit",
        label: "坐姿",
        groundContact: "both-feet",
        controls: {
            "torso.pitch": 8,
            "head.pitch": -3,
            "leftShoulder.pitch": 2,
            "rightShoulder.pitch": 2,
            "leftShoulder.twist": 20,
            "rightShoulder.twist": -20,
            "leftElbow.bend": 70,
            "rightElbow.bend": 70,
            "leftHip.pitch": 88,
            "rightHip.pitch": 88,
            "leftKnee.bend": 90,
            "rightKnee.bend": 90,
            "leftFoot.pitch": -2,
            "rightFoot.pitch": -2,
        },
    },
    {
        id: "crouch",
        label: "蹲下",
        groundContact: "both-feet",
        controls: {
            "torso.pitch": 28,
            "head.pitch": -12,
            "leftShoulder.pitch": 20,
            "rightShoulder.pitch": 20,
            "leftShoulder.twist": 20,
            "rightShoulder.twist": -20,
            "leftElbow.bend": 55,
            "rightElbow.bend": 55,
            "leftHip.pitch": 100,
            "rightHip.pitch": 100,
            "leftKnee.bend": 125,
            "rightKnee.bend": 125,
            "leftFoot.pitch": -25,
            "rightFoot.pitch": -25,
        },
    },
    {
        id: "kneel-one",
        label: "单膝跪",
        groundContact: "left-foot-right-knee",
        controls: {
            "body.yaw": -4,
            "torso.pitch": 8,
            "head.pitch": -4,
            "leftShoulder.pitch": 2,
            "leftShoulder.twist": 20,
            "leftElbow.bend": 70,
            "rightShoulder.pitch": -5,
            "rightShoulder.spread": 8,
            "rightElbow.bend": 12,
            "leftHip.pitch": 95,
            "leftKnee.bend": 109,
            "leftFoot.pitch": -24,
            "rightKnee.bend": 135,
            "rightFoot.pitch": -65,
        },
    },
    {
        id: "kneel-two",
        label: "双膝跪",
        groundContact: "both-knees",
        controls: {
            "torso.pitch": 3,
            "head.pitch": -2,
            "leftShoulder.pitch": -5,
            "rightShoulder.pitch": -5,
            "leftShoulder.spread": -4,
            "rightShoulder.spread": 4,
            "leftElbow.bend": 8,
            "rightElbow.bend": 8,
            "leftKnee.bend": 105,
            "rightKnee.bend": 105,
            "leftFoot.pitch": -120,
            "rightFoot.pitch": -120,
        },
    },
    {
        id: "hands-on-hips",
        label: "叉腰",
        groundContact: "both-feet",
        controls: {
            "leftShoulder.pitch": -30,
            "rightShoulder.pitch": -30,
            "leftShoulder.twist": 28,
            "rightShoulder.twist": -28,
            "leftElbow.bend": 85,
            "rightElbow.bend": 85,
            "leftHand.roll": -15,
            "rightHand.roll": 15,
        },
    },
    {
        id: "lean",
        label: "倚靠",
        groundContact: "right-foot",
        controls: {
            "body.roll": -12,
            "torso.roll": 4,
            "head.roll": 7,
            "leftHip.spread": -5,
            "rightHip.spread": 5,
            "leftKnee.bend": 7,
            "leftShoulder.spread": -8,
            "rightShoulder.spread": 4,
        },
    },
    {
        id: "bow",
        label: "鞠躬",
        groundContact: "both-feet",
        controls: {
            "torso.pitch": 50,
            "head.pitch": -14,
            "leftShoulder.pitch": 45,
            "rightShoulder.pitch": 45,
            "leftShoulder.spread": -4,
            "rightShoulder.spread": 4,
            "leftElbow.bend": 6,
            "rightElbow.bend": 6,
            "leftKnee.bend": 4,
            "rightKnee.bend": 4,
            "leftFoot.pitch": -4,
            "rightFoot.pitch": -4,
        },
    },
    {
        id: "think",
        label: "思考",
        groundContact: "both-feet",
        controls: {
            "head.pitch": 8,
            "head.roll": 4,
            "rightShoulder.pitch": 50,
            "rightShoulder.spread": -45,
            "rightShoulder.twist": -30,
            "rightElbow.bend": 125,
            "rightHand.pitch": 12,
            "rightHand.twist": -12,
            "rightHand.roll": -18,
            "leftShoulder.pitch": 22,
            "leftShoulder.spread": 20,
            "leftShoulder.twist": 55,
            "leftElbow.bend": 100,
            "leftHand.roll": 10,
        },
    },
    {
        id: "fight",
        label: "格斗",
        groundContact: "left-foot",
        controls: {
            "body.pitch": 7,
            "body.yaw": -8,
            "torso.yaw": 8,
            "head.yaw": 5,
            "leftShoulder.pitch": 35,
            "rightShoulder.pitch": 35,
            "leftShoulder.twist": 35,
            "rightShoulder.twist": -35,
            "leftElbow.bend": 110,
            "rightElbow.bend": 110,
            "leftHip.pitch": 8,
            "rightHip.pitch": -8,
            "leftHip.spread": -20,
            "rightHip.spread": 20,
            "leftKnee.bend": 18,
            "rightKnee.bend": 24,
            "leftFoot.roll": -6,
            "rightFoot.roll": 6,
        },
    },
    {
        id: "kick",
        label: "踢球",
        groundContact: "left-foot",
        controls: {
            "body.pitch": -8,
            "torso.yaw": -8,
            "leftShoulder.spread": -36,
            "rightShoulder.spread": 36,
            "leftElbow.bend": 18,
            "rightElbow.bend": 18,
            "leftHip.pitch": -5,
            "leftKnee.bend": 8,
            "leftFoot.pitch": -13,
            "rightHip.pitch": 72,
            "rightKnee.bend": 25,
            "rightFoot.pitch": 47,
            "rightFoot.twist": -8,
        },
    },
    {
        id: "throw",
        label: "投掷",
        groundContact: "right-foot",
        controls: {
            "body.pitch": 4,
            "body.yaw": -14,
            "torso.yaw": 16,
            "head.yaw": -8,
            "rightShoulder.pitch": 112,
            "rightShoulder.spread": 102,
            "rightShoulder.twist": 5,
            "rightElbow.bend": 132,
            "rightHand.pitch": -12,
            "rightHand.roll": 18,
            "leftShoulder.pitch": 82,
            "leftShoulder.spread": -4,
            "leftElbow.bend": 8,
            "leftHand.pitch": -8,
            "leftHip.pitch": 22,
            "rightHip.pitch": -14,
            "leftHip.spread": -12,
            "rightHip.spread": 16,
            "leftKnee.bend": 30,
            "rightKnee.bend": 16,
            "leftFoot.pitch": -8,
            "rightFoot.roll": 6,
        },
    },
    {
        id: "push",
        label: "推进",
        groundContact: "left-foot",
        controls: {
            "body.pitch": 8,
            "torso.pitch": 10,
            "head.pitch": -5,
            "leftShoulder.pitch": 88,
            "rightShoulder.pitch": 88,
            "leftShoulder.spread": -4,
            "rightShoulder.spread": 4,
            "leftElbow.bend": 8,
            "rightElbow.bend": 8,
            "leftHand.pitch": -10,
            "rightHand.pitch": -10,
            "leftHip.pitch": 30,
            "rightHip.pitch": -18,
            "leftHip.spread": -10,
            "rightHip.spread": 12,
            "leftKnee.bend": 40,
            "rightKnee.bend": 22,
            "leftFoot.pitch": -10,
            "rightFoot.pitch": -40,
        },
    },
    {
        id: "wave",
        label: "招手",
        groundContact: "both-feet",
        controls: {
            "rightShoulder.pitch": 72,
            "rightShoulder.spread": 72,
            "rightShoulder.twist": 12,
            "rightElbow.bend": 118,
            "rightHand.roll": -20,
            "rightHand.pitch": 12,
            "rightHand.twist": 10,
            "leftShoulder.pitch": -8,
            "leftShoulder.spread": -5,
            "leftElbow.bend": 12,
        },
    },
    {
        id: "reach",
        label: "伸手",
        groundContact: "both-feet",
        controls: {
            "torso.pitch": 3,
            "rightShoulder.pitch": 85,
            "rightElbow.bend": 10,
            "rightHand.pitch": -5,
            "leftShoulder.pitch": -6,
        },
    },
    {
        id: "cross-arms",
        label: "抱臂",
        groundContact: "both-feet",
        controls: {
            "leftShoulder.pitch": 22,
            "leftShoulder.spread": 20,
            "leftShoulder.twist": 55,
            "leftElbow.bend": 100,
            "leftHand.pitch": -10,
            "leftHand.roll": -8,
            "rightShoulder.pitch": 22,
            "rightShoulder.spread": -20,
            "rightShoulder.twist": -55,
            "rightElbow.bend": 100,
            "rightHand.pitch": -10,
            "rightHand.roll": 8,
        },
    },
    {
        id: "phone",
        label: "看手机",
        groundContact: "both-feet",
        controls: {
            "head.pitch": 22,
            "leftShoulder.pitch": 32,
            "leftShoulder.twist": 35,
            "leftElbow.bend": 108,
            "leftHand.pitch": 12,
            "leftHand.twist": 8,
            "leftHand.roll": 10,
            "rightShoulder.pitch": 35,
            "rightShoulder.twist": -35,
            "rightElbow.bend": 110,
            "rightHand.pitch": 12,
            "rightHand.twist": -8,
            "rightHand.roll": -10,
        },
    },
] as const;
